### ISSUE TITLE
Not able to figure what error is this when we run python files (AttributeError: 'Namespace' object has no attribute 'exp_name')

### ISSUE THREAD

**Issue by ShreyasK-alt** [SYSU-STAR/H2-Mapping#37]
I completed setting up H2 mapping according to the guide but when it comes to running H2 Mapping on intel realsense live data there isnt any correct information in the tutorial so went ahead with these steps:

1. In first terminal started `roscore`
2. second terminal parallely, start roslaunch for realsense camera
3. checked and updated the realsence.yaml file on both directories of mapping and dvins directory  (/H2-Mapping/mapping/configs/realsense/realsense.yaml  and /H2-Mapping/src/dvins/config/realsense/realsense_color_config.yaml )
4. started roslaunch `roslaunch vins_estimator realsense.launch`
5. Things seem to be in place there were some errors or warnings in the vins estimator roslaunch. please check with attached outputs
6. `conda activate h2mapping`
7. and started mapping file this way: `python3 -W ignore demo/run_mapping.py configs/realsense/realsense.yaml -run_ros` in mapping folder. this turns out to give error.

Note: `source devel/setup.bash `was done when ever terminal was opened.

Outputs:
1. Roslaunch for realsense camera:
```
SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_infra: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: 200
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: linear_interpolation
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /camera/stereo_module/emitter_enabled: 0
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [26531]
process[camera/realsense2_camera-2]: started with pid [26532]
[ INFO] [1719684642.309790106]: Initializing nodelet with 16 worker threads.
[ INFO] [1719684642.382244201]: RealSense ROS v2.3.2
[ INFO] [1719684642.382287222]: Built with LibRealSense v2.50.0
[ INFO] [1719684642.382308310]: Running with LibRealSense v2.50.0
[ INFO] [1719684642.408644668]:  
[ INFO] [1719684642.701740659]: Device with serial number 243522070607 was found.

[ INFO] [1719684642.701764291]: Device with physical ID 4-8-2 was found.
[ INFO] [1719684642.701772166]: Device with name Intel RealSense D435I was found.
[ INFO] [1719684642.701990924]: Device with port number 4-8 was found.
[ INFO] [1719684642.702002239]: Device USB type: 3.2
[ INFO] [1719684642.703203062]: getParameters...
[ INFO] [1719684642.722062716]: setupDevice...
[ INFO] [1719684642.722084348]: JSON file is not provided
[ INFO] [1719684642.722098965]: ROS Node Namespace: camera
[ INFO] [1719684642.722114055]: Device Name: Intel RealSense D435I
[ INFO] [1719684642.722130346]: Device Serial No: 243522070607
[ INFO] [1719684642.722144684]: Device physical port: 4-8-2
[ INFO] [1719684642.722158751]: Device FW version: 05.13.00.50
[ INFO] [1719684642.722177699]: Device Product ID: 0x0B3A
[ INFO] [1719684642.722191713]: Enable PointCloud: Off
[ INFO] [1719684642.722205031]: Align Depth: On
[ INFO] [1719684642.722217799]: Sync Mode: On
[ INFO] [1719684642.722258730]: Device Sensors: 
[ INFO] [1719684642.800518183]: Stereo Module was found.
[ INFO] [1719684642.809931113]: RGB Camera was found.
[ INFO] [1719684642.810031811]: Motion Module was found.
[ INFO] [1719684642.810049362]: (Infrared, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1719684642.810058033]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1719684642.810329798]: num_filters: 1
[ INFO] [1719684642.810350070]: Setting Dynamic reconfig parameters.
[ INFO] [1719684646.318915332]: Done Setting Dynamic reconfig parameters.
[ INFO] [1719684646.319465049]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1719684646.319573779]: infra1 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1719684646.319683040]: infra2 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1719684646.319956607]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1719684646.321378729]: gyro stream is enabled - fps: 200
[ WARN] [1719684646.321402169]: No mathcing profile found for accel with fps=250
[ WARN] [1719684646.321414073]: Using default profile instead.
[ INFO] [1719684646.321425079]: accel stream is enabled - fps: 100
[ INFO] [1719684646.321440949]: setupPublishers...
[ INFO] [1719684646.323770529]: Expected frequency for depth = 30.00000
[ INFO] [1719684646.345136918]: Expected frequency for infra1 = 30.00000
[ INFO] [1719684646.357837442]: Expected frequency for infra2 = 30.00000
[ INFO] [1719684646.370033771]: Expected frequency for color = 30.00000
[ INFO] [1719684646.380065613]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1719684646.392352807]: Start publisher IMU
[ INFO] [1719684646.393386954]: setupStreams...
 29/06 23:40:46,696 WARNING [140324939433728] (ds5-motion.cpp:473) IMU Calibration is not available, default intrinsic and extrinsic will be used.
[ WARN] [1719684646.981118650]: 
[ WARN] [1719684646.981198464]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 29/06 23:40:47,088 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
[ INFO] [1719684647.139241834]: SELECTED BASE:Depth, 0
[ INFO] [1719684647.149583126]: RealSense Node Is Up!
 29/06 23:40:47,211 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,262 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,313 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,465 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,516 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,566 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,617 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,668 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,719 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,751 ERROR [140323733935872] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 130
 29/06 23:40:47,769 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,820 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,871 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,922 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:47,973 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,023 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,074 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,086 ERROR [140323708757760] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 131
 29/06 23:40:48,124 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,175 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,226 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,276 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,327 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,378 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,428 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,479 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,530 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,581 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:48,935 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:49,086 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:40:49,137 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
[ WARN] [1719684649.320666358]: Hardware Notification:Depth stream start failure,1.71968e+12,Error,Hardware Error
 29/06 23:41:47,851 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:31,949 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:38,004 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:38,054 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:48,110 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:48,161 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:49,212 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:49,263 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:50,314 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:50,365 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:51,416 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:51,467 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:55,519 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:55,570 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:56,621 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:56,672 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
 29/06 23:42:57,723 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:57,773 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:58,825 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:58,875 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
 29/06 23:42:59,926 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:42:59,976 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
 29/06 23:43:01,027 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:01,078 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:02,129 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:02,180 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
 29/06 23:43:13,238 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:13,288 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:14,339 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:14,390 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:15,441 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:15,491 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:15,934 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:43:16,543 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:16,593 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:16,938 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:43:17,943 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:43:19,645 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:19,696 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:20,747 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:20,798 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:24,851 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 29/06 23:43:37,042 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:43:38,047 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:43:39,052 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:43:52,923 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:43:56,977 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:44:49,067 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:45:31,155 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:45:35,208 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:45:53,276 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:48:25,458 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:49:34,556 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:50:39,659 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:50:39,710 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:50:40,240 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:50:41,244 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:50:42,249 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:50:48,766 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:50:48,816 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:50:49,868 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:50:49,919 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:50:50,970 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:50:51,021 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:52:07,120 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:54:45,278 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:04,602 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:55:05,608 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:55:06,613 ERROR [140323611203328] (ds5-options.cpp:88) Asic Temperature value is not valid!
 29/06 23:55:15,358 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:15,409 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:18,462 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:18,513 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:22,568 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:22,619 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:26,674 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:26,724 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:27,776 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:27,827 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:29,879 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 29/06 23:55:29,930 WARNING [140324914255616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
```

2. roslaunch for vins estimater: 
```
SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /vins_estimator/config_file: /home/usr1/H2-Ma...
 * /vins_estimator/vins_folder: /home/usr1/H2-Ma...

NODES
  /
    rvizvisualisation (rviz/rviz)
    vins_estimator (vins_estimator/vins_estimator)

ROS_MASTER_URI=http://localhost:11311

process[vins_estimator-1]: started with pid [31223]
process[rvizvisualisation-2]: started with pid [31224]
[ INFO] [1719684976.358124709]: init begins
[ INFO] [1719684976.364175105]: Loaded config_file: /home/usr1/H2-Mapping/src/dvins/vins_estimator/../config/realsense/realsense_color_config.yaml
[ INFO] [1719684976.365675434]: Loaded vins_folder: /home/usr1/H2-Mapping/src/dvins/vins_estimator/../config/../
result path /home/tony-ws1/output//vins_result_no_loop.csv
/home/tony-ws1/output/ not exists, trying to create it 
/home/tony-ws1 not exists, trying to create it 
Failed to create folder /home/tony-ws1 
[ INFO] [1719684976.365735081]: ROW: 480 COL: 640 
[ WARN] [1719684976.365742614]:  fix extrinsic param 
[ INFO] [1719684976.365792209]: Extrinsic_R : 
  -0.0017685 -0.000467898     0.999998
   -0.999948   -0.0100627  -0.00177312
   0.0100635    -0.999949 -0.000450078
[ INFO] [1719684976.365804144]: Extrinsic_T : 
0.0248916 0.0222261 0.0815515
[ INFO] [1719684976.365813669]: Synchronized sensors, fix time offset: 0
[ INFO] [1719684976.365832379]: reading paramerter of camera /home/usr1/H2-Mapping/src/dvins/vins_estimator/../config/realsense/realsense_color_config.yaml
[ WARN] [1719684976.365962142]: Waiting for image and imu...
[ INFO] [1719684977.806301891]: IMU excitation not enouth!
[ INFO] [1719684977.907847657]: IMU excitation not enouth!
[ INFO] [1719684978.001058363]: IMU excitation not enouth!
[ INFO] [1719684978.100975256]: IMU excitation not enouth!
[ INFO] [1719684978.205375697]: IMU excitation not enouth!
[ INFO] [1719684978.303834582]: IMU excitation not enouth!
[ INFO] [1719684978.404345591]: IMU excitation not enouth!
[ INFO] [1719684978.506868649]: IMU excitation not enouth!
[ INFO] [1719684978.607205211]: IMU excitation not enouth!
[ INFO] [1719684978.706386889]: IMU excitation not enouth!
```

3. `python3 -W ignore demo/run_mapping.py configs/realsense/realsense.yaml -run_ros` :

```
Traceback (most recent call last):
  File "demo/run_mapping.py", line 25, in <module>
    slam = H2Mapping(args)
  File "/home/vt008/H2-Mapping/mapping/src/H2Mapping.py", line 10, in __init__
    self.logger = BasicLogger(args)
  File "/home/vt008/H2-Mapping/mapping/src/loggers.py", line 20, in __init__
    args.log_dir, args.exp_name, self.get_random_time_str())
AttributeError: 'Namespace' object has no attribute 'exp_name'
```

Can you please be clear on what does this line mean(To execute the code similar to the provided demo.)

Can you please provide even more clear guide on how to run H2 mapping on live realsense input?

**Comment by JIANG-CX** [comment]
I apologize for not addressing your issue earlier; I just noticed it now. 

1. Regarding the VINS tracking, I'm wondering if RViz has displayed the estimated trajectory. If it has, that means the system is running successfully. However, I noticed the message "IMU excitation not enough!" appears. As you are using monocular VIO, you need to move the RealSense camera for its VIO initialization.

2. Concerning the "AttributeError: 'Namespace' object has no attribute 'exp_name'" error, please use the `configs/realsense/tower.yaml` file instead of `configs/realsense/realsense.yaml`. The latter is a base configuration file for `configs/realsense/tower.yaml`, not the one you need to use. You can modify parameters (like max_depth and bound) in `configs/realsense/tower.yaml` to suit your experimental scenarios.

Once again, I apologize for missing this issue.
